<a href="https://colab.research.google.com/github/Sarfaraz-Ali/NLP/blob/main/Fake_News_Classfier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
#############DATASET LINK ########
# https://drive.google.com/file/d/19FoplQJJWGdxPi88mB8-jOBxJDmZs58h/view?usp=sharing

In [ ]:
import nltk
nltk.download('all')

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import pandas as pd

In [15]:
df=pd.read_csv('/content/drive/MyDrive/NLP/fake_train.csv')

In [16]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [17]:
  df.isna().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [18]:
df.shape

(20800, 5)

In [19]:
df.dropna(inplace = True)

In [20]:
df.shape

(18285, 5)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18285 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      18285 non-null  int64 
 1   title   18285 non-null  object
 2   author  18285 non-null  object
 3   text    18285 non-null  object
 4   label   18285 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 857.1+ KB


In [24]:
X=df.drop(['label'],axis=1)

In [25]:
y=df['label']

In [26]:
import tensorflow as tf

In [27]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [28]:
voc_size=5000

In [29]:
messages = X.copy()

messages.reset_index(inplace=True,drop=True)

In [32]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
18280  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [34]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [78]:
def stem(message):
  corp = []
  for i in range(0, len(message)):
      review = re.sub('[^a-zA-Z]', ' ', message[i])
      review = review.lower()
      review = review.split()
      
      review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
      review = ' '.join(review)
      corp.append(review)

  return corp

In [79]:
message = messages['title']
corpus = stem(message)

In [80]:
message[0:5]

0    House Dem Aide: We Didn’t Even See Comey’s Let...
1    FLYNN: Hillary Clinton, Big Woman on Campus - ...
2                    Why the Truth Might Get You Fired
3    15 Civilians Killed In Single US Airstrike Hav...
4    Iranian woman jailed for fictional unpublished...
Name: title, dtype: object

In [81]:
corpus[:5]

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri']

In [39]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr[:10]

[[4921, 2163, 1468, 8, 1923, 95, 3246, 514, 2878, 2158],
 [275, 1533, 1800, 2376, 4603, 3632, 4121],
 [2140, 3943, 3615, 3362],
 [110, 857, 3205, 2054, 3212, 4721],
 [1937, 4603, 3037, 3529, 2843, 1896, 4603, 188, 948, 1039],
 [3984,
  3625,
  1814,
  1411,
  4883,
  3784,
  920,
  4767,
  3763,
  2631,
  299,
  3043,
  816,
  4280,
  4121],
 [4150, 3509, 2505, 3561, 520, 2822, 3661, 71, 1646, 2925, 250],
 [4906, 1789, 3583, 2945, 4294, 1322, 3784, 4511, 1646, 2925, 250],
 [762, 546, 1437, 4025, 181, 3954, 2328, 1632, 3784, 3239],
 [3124, 29, 2973, 1240, 1276, 2804, 1583, 2155]]

In [41]:
sent_length=20

In [82]:
embedded_docs=pad_sequences(onehot_repr, maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  514 2878 2158]
 [   0    0    0 ... 4603 3632 4121]
 [   0    0    0 ... 3943 3615 3362]
 ...
 [   0    0    0 ... 1646 2925  250]
 [   0    0    0 ... 4307 3816 1674]
 [   0    0    0 ... 1690 4651 1102]]


In [49]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 4921,
       2163, 1468,    8, 1923,   95, 3246,  514, 2878, 2158], dtype=int32)

In [50]:
## Creating Model

from tensorflow.keras.layers import Dropout

embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.4))
#model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 dropout (Dropout)           (None, 20, 40)            0         
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [51]:
len(embedded_docs),y.shape

(18285, (18285,))

In [52]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [53]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_final,y_final,test_size=0.2,random_state=42)

In [54]:
#### Fitting the model
model.fit(X_train,y_train,epochs=10,validation_data=(X_test,y_test),batch_size=64)

Epoch 1/10
229/229 [==============================] - 12s 37ms/step - loss: 0.3246 - accuracy: 0.8495 - val_loss: 0.2091 - val_accuracy: 0.9098
Epoch 2/10
229/229 [==============================] - 7s 32ms/step - loss: 0.1452 - accuracy: 0.9442 - val_loss: 0.2014 - val_accuracy: 0.9147
Epoch 3/10
229/229 [==============================] - 7s 32ms/step - loss: 0.1077 - accuracy: 0.9595 - val_loss: 0.2315 - val_accuracy: 0.9117
Epoch 4/10
229/229 [==============================] - 7s 32ms/step - loss: 0.0808 - accuracy: 0.9701 - val_loss: 0.2709 - val_accuracy: 0.9150
Epoch 5/10
229/229 [==============================] - 7s 32ms/step - loss: 0.0606 - accuracy: 0.9778 - val_loss: 0.2655 - val_accuracy: 0.9070
Epoch 6/10
229/229 [==============================] - 7s 32ms/step - loss: 0.0485 - accuracy: 0.9844 - val_loss: 0.3406 - val_accuracy: 0.9048
Epoch 7/10
229/229 [==============================] - 7s 32ms/step - loss: 0.0338 - accuracy: 0.9899 - val_loss: 0.4431 - val_accuracy: 0.907